SET /P _inputfile= Please enter an input file... 
SET /P _outputfile= Please enter an output file name... 
SET /P _targetfps= Please enter target fps... 
ffmpeg -y -i %_inputfile% -c copy -f h264 %_outputfile%.h264
ffmpeg -y -r %_targetfps% -i %_outputfile%.h264 -c copy %_outputfile%
del %_outputfile%.h264
pause