SET /P _inputfile= Please enter an input file (with extension)... 
SET /P _outputfile= Please enter an output file name (without extension)... 
SET /P _outext= Please enter output extension... 
SET /P _targetfps= Please enter target fps... 
ffmpeg -y -i %_inputfile% -c copy -f h264 %_outputfile%.h264
ffmpeg -y -r %_targetfps% -i %_outputfile%.h264 -c copy %_outputfile%%_outext%
del "%_outputfile%.h264"
ECHO DONE